name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions"

      - name: Version package
        run: 'npm version ${{ github.event.release.tag_name }} -m "chore: bump version to %s"'

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes to GitHub
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
