name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Build, Lint, Format, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build files
        run: yarn build

      - name: Run ESLint
        run: yarn lint:check

      - name: Run Prettier
        run: yarn format:check

      - name: Run Tests
        run: yarn test
